global:
  smtp_smarthost: 'smtp.qq.com:587'
  smtp_from: '1769250028@qq.com'
  smtp_auth_username: '1769250028@qq.com'
  smtp_auth_password: 'vztcabveuaxdbiff'
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_by: ['container']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
- name: 'email-alert'
  email_configs:
  - to: '1769250028@qq.com'
    send_resolved: false
    headers:
      Subject: '【容器监控告警】{{ .CommonLabels.container }} 出现异常'

    html: |
      <html>
      <body style="font-family:Arial;padding:20px;">
        <h2 style="color:red;">容器告警通知</h2>

        <p><b>容器：</b>{{ .CommonLabels.container }}</p>
        <p><b>告警数量：</b>{{ len .Alerts }}</p>

        {{ range .Alerts }}
        <hr>
        <p><b>告警：</b>{{ .Annotations.summary }}</p>
        <p><b>说明：</b>{{ .Annotations.description }}</p>
        <p><b>级别：</b>{{ .Labels.severity }}</p>
        <p><b>时间：</b>{{ .StartsAt }}</p>
        {{ end }}

      </body>
      </html>
